name: hydrium.co CI
on: 
  push: 
    branches: 
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout do repositório
        uses: actions/checkout@1
      -name: Deploy para meu hosting
        uses: easing themes/ssh-deploy@main
        env:  
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOSTS }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
