name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt 3
        run: npm run build

      # - name: Test Nuxt 3
      #   run: npm run preview

      # - name: Post Nuxt 3
      #   run: npm run prepare

      - name: Deploy via PM2
        run: |
          npm install pm2 -g
          pm2 delete my-app || true
          pm2 start .output/server/index.mjs --name my-app
